name: Updater index.yaml 

# on:
#   push:
#     branches:
#       - master
#     tags:
#       - '*'
on: repository_dispatch
    
jobs:
  push_to_registries:
    name: Updater index.yaml 
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: master
        
      - name: update index.yaml
        run: helm repo index .  
        
      - name: check
        run: cat index.yaml
          
      - name: Add email
        run: git config --global user.email ${{ secrets.EMAIL }}
      
      - name: Add username
        run: git config --global user.name "dgaponcic"    

      - name: Check remotes
        run: git remote -v
        
      - name: checkout
        run: git checkout master
        
      - name: Git add
        run: git add .


      - name: Git status
        run: git status 
        
      - name: Git commit
        run: git commit -m "update configuration with new index.yaml"
        
      - name: Git push
        run: git push origin master
      
